apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: metro
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64("postgres")
  POSTGRES_PASSWORD: cG9zdGdyZXM=   # base64("postgres")
  POSTGRES_DB: bWV0cm9jYXJwb29s     # base64("metrocarpool")
